# Generated by Django 3.0.3 on 2020-02-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('-name',), 'verbose_name': 'Параметр', 'verbose_name_plural': 'Список параметров'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Перечень параметров продукта'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='filename',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Category', verbose_name='Категория'),
        ),
    ]
