# Generated by Django 3.0.3 on 2020-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200212_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparameter',
            name='value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Значение'),
        ),
    ]
