# Generated by Django 3.0.3 on 2020-02-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200219_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True, verbose_name='статус получения заказов'),
        ),
    ]
